### PR TITLE
update: falco-plugin for Falco 0.32

### PR DESCRIPTION
**Pull request by leogr**
# Adjust falco-plugin for Falco 0.32

This PRs introduces mandatory changes to make the falco-plugin compatible with Falco 0.32.

It was necessary because Falco 0.32 introduces some backward-incompatible changes in the plugin API.

cc @alban 

## How to use

Try the plugin with Falco 0.32.

## Testing done

[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]

### CODE REVIEW

**Comment by rata** [comment]
@leogr thanks for the PR! I'll leave this to @alban :)

**Comment by leogr** [comment]
> @leogr thanks for the PR! I'll leave this to @alban :)

You're welcome :)

PS
Currently, this PR is just a draft, I'll set it ready for review once Falco 0.32 is out.

**Comment by alban** [comment]
LGTM (once Falco is out) :)

**Comment by leogr** [comment]
Any updates?

**Pull request merged**
