### PR TITLE
[Add] add container runtime requirement when install seccompAgent

### PR DESCRIPTION
**Pull request by brness**
# [Title: describe the change in one sentence]
enrich the container runtime constraints in install docs.
[ describe the change in 1 - 3 paragraphs ]

## How to use
check if the words in install docs make sense 
[ describe what reviewers need to do in order to validate this PR ]

## Testing done
no 
[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]
@alban @rata

### CODE REVIEW

**Review by rata — COMMENTED** [review]
@brness thanks, LGTM! Do you mind adding some link in the README (I mean in the top level README) to point here? The readme there might be confusing (probably confused you?) that you can just run that on any cluster, which is not true

**Comment by brness** [comment]
> @brness thanks, LGTM! Do you mind adding some link in the README (I mean in the top level README) to point here? The readme there might be confusing (probably confused you?) that you can just run that on any cluster, which is not true

OK, how about now? Should I emphasis the importance of the requirements by widening the fonts of the word?

**Review by alban — APPROVED** [review]
Thanks!

**Comment by rata** [comment]
Looks great, thanks!

**Comment by brness** [comment]
It's my pleasure to work with your all~~

**Pull request merged**
