### PR TITLE
Accept larger OCI specs

### PR DESCRIPTION
**Pull request by dgl**
# Accept larger OCI specs

In some cases these can be much larger than 4KB, let's use 32K for now; this should be refactored to do the OOB read and then if n == MaxStateLen do a normal read for the rest, as 32K is still an arbitrary limit that other parts of the ecosystem don't apply.

## How to use

Configure a container with a lot of volumes or otherwise something which results in quite a complex OCI spec.

## Testing done

I saw an error like this on a container:

```
time="2023-01-25T04:58:54Z" level=error msg="Error on receiving seccomp fd" err="recvfd: incorrect number of bytes read (n=4096 oobn=24)" socket=/run/seccomp-agent.socket
```

Upped the buffer size and see it works with that container.

### CODE REVIEW

**Comment by mqasimsarfraz** [comment]
I hit this as well while testing #32 for `cri-o`. Since `cri-o` contains more information so maybe it goes beyond the limit e.g you can some of the additional information below:

```
time="2023-02-09T16:58:56Z" level=debug msg="New seccomp fd received on socket" annotations="map[io.container.manager:cri-o io.kubernetes.container.hash:68792412 io.kubernetes.container.name:container1 io.kubernetes.container.restartCount:0 io.kubernetes.container.terminationMessagePath:/dev/termination-log io.kubernetes.container.terminationMessagePolicy:File io.kubernetes.cri-o.Annotations:{\"io.kubernetes.container.hash\":\"68792412\",\"io.kubernetes.container.restartCount\":\"0\",\"io.kubernetes.container.terminationMessagePath\":\"/dev/termination-log\",\"io.kubernetes.container.terminationMessagePolicy\":\"File\",\"io.kubernetes.pod.terminationGracePeriod\":\"30\"} io.kubernetes.cri-o.ContainerID:da3ed012618185c20063671eb36cd6bce8222b5995b49d521a0e0133c4b73b0d io.kubernetes.cri-o.ContainerType:container io.kubernetes.cri-o.Created:2023-02-09T16:58:56.52144096Z io.kubernetes.cri-o.IP.0:10.244.0.12 io.kubernetes.cri-o.Image:430e2ddb3f8baa1466161e7d5287ffd730a2d737214535da4e0fae894030b278 io.kubernetes.cri-o.ImageName:quay.io/kinvolk/seccompagent:main-dfdc62e io.kubernetes.cri-o.ImageRef:430e2ddb3f8baa1466161e7d5287ffd730a2d737214535da4e0fae894030b278 io.kubernetes.cri-o.Labels:{\"io.kubernetes.container.name\":\"container1\",\"io.kubernetes.pod.name\":\"mypod\",\"io.kubernetes.pod.namespace\":\"default\",\"io.kubernetes.pod.uid\":\"27bb02ba-ee5c-47f9-9557-3f10db4400f9\"} io.kubernetes.cri-o.LogPath:/var/log/pods/default_mypod_27bb02ba-ee5c-47f9-9557-3f10db4400f9/container1/0.log io.kubernetes.cri-o.Metadata:{\"name\":\"container1\"} io.kubernetes.cri-o.MountPoint:/var/lib/containers/storage/overlay/3f73065b571bc8070b1357e1d9e4d1e06b3747f41005437f00d9923b7348a2d2/merged io.kubernetes.cri-o.Name:k8s_container1_mypod_default_27bb02ba-ee5c-47f9-9557-3f10db4400f9_0 io.kubernetes.cri-o.ResolvPath:/run/containers/storage/overlay-containers/b75102f9548f54e954506d5600cc2108c9a09203919cd1b7015eccf7b9808d47/userdata/resolv.conf io.kubernetes.cri-o.SandboxID:b75102f9548f54e954506d5600cc2108c9a09203919cd1b7015eccf7b9808d47 io.kubernetes.cri-o.SandboxName:k8s_mypod_default_27bb02ba-ee5c-47f9-9557-3f10db4400f9_0 io.kubernetes.cri-o.SeccompProfilePath:localhost//var/lib/kubelet/seccomp/notify-dangerous.json io.kubernetes.cri-o.Stdin:false io.kubernetes.cri-o.StdinOnce:false io.kubernetes.cri-o.TTY:false io.kubernetes.cri-o.Volumes:[{\"container_path\":\"/etc/hosts\",\"host_path\":\"/var/lib/kubelet/pods/27bb02ba-ee5c-47f9-9557-3f10db4400f9/etc-hosts\",\"readonly\":false,\"propagation\":0,\"selinux_relabel\":false},{\"container_path\":\"/dev/termination-log\",\"host_path\":\"/var/lib/kubelet/pods/27bb02ba-ee5c-47f9-9557-3f10db4400f9/containers/container1/7886aa8a\",\"readonly\":false,\"propagation\":0,\"selinux_relabel\":false},{\"container_path\":\"/var/run/secrets/kubernetes.io/serviceaccount\",\"host_path\":\"/var/lib/kubelet/pods/27bb02ba-ee5c-47f9-9557-3f10db4400f9/volumes/kubernetes.io~projected/kube-api-access-r4w6s\",\"readonly\":true,\"propagation\":0,\"selinux_relabel\":false}] io.kubernetes.pod.name:mypod io.kubernetes.pod.namespace:default io.kubernetes.pod.terminationGracePeriod:30 io.kubernetes.pod.uid:27bb02ba-ee5c-47f9-9557-3f10db4400f9 kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"metadata\":{\"annotations\":{},\"name\":\"mypod\",\"namespace\":\"default\"},\"spec\":{\"containers\":[{\"args\":[\"-c\",\"sleep infinity\"],\"command\":[\"sh\"],\"image\":\"quay.io/kinvolk/seccompagent:main-dfdc62e\",\"imagePullPolicy\":\"Never\",\"name\":\"container1\"}],\"restartPolicy\":\"Never\",\"securityContext\":{\"seccompProfile\":{\"localhostProfile\":\"notify-dangerous.json\",\"type\":\"Localhost\"}}}}\n kubernetes.io/config.seen:2023-02-09T16:58:56.157584977Z kubernetes.io/config.source:api org.systemd.property.After:['crio.service'] org.systemd.property.CollectMode:'inactive-or-failed' org.systemd.property.DefaultDependencies:true org.systemd.property.TimeoutStopUSec:uint64 30000000]" fd=7 id=da3ed012618185c20063671eb36cd6bce8222b5995b49d521a0e0133c4b73b0d pid=7144 pid1=7144
```

**Comment by stackedsax** [comment]
Hey there @mqasimsarfraz, are the right person to review @dgl's PR here?

**Comment by mqasimsarfraz** [comment]
> Hey there @mqasimsarfraz, are the right person to review @dgl's PR here?

I believe @alban can review this? I am unaware of side effects of increasing `MaxStateLen`.

**Review by rata — APPROVED** [review]
LGTM

@dgl wanna work also in the read by chunks, so it works with bigger thngs to? Or wanna add a TODO comment and create an issue here in github so we don't easily forget about it?

**Comment by alban** [comment]
Thanks for the patch! Sorry for the delay.

**Pull request merged**
